version: "3.7"

services:
  pgvector:
    container_name: pgvector
    image: ankane/pgvector
    ports:
      - ${DB_PORT:?}:5432
    volumes:
      - pgvector-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}

volumes:
  pgvector-data:
